[package]
name = "server"
version = "0.1.0"
authors = ["Elliot W. <elliotwhybrow@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3.3.2"
actix-cors = "0.5.3"
serde = {version = "^1", features = ["derive"]}
serde_json = "*"
fastrand = "1.4.0"