[package]
name = "kascreech"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio-tungstenite = "0.15.0"
actix-web = "^3.3"
actix-cors = "^0.5"
actix-files = "^0.5"
serde = {version = "^1", features = ["derive"]}
serde_json = "*"
fastrand = "^1.4"
