[package]
name = "kascreech"
version = "0.1.0"
edition = "2021"

[dependencies]
humphrey = { version = "^0.5.5", features = ["tls"] }
humphrey_ws = "^0.3.3"
humphrey_json = "^0.1.0"
jasondb = "^0.2.4"
getrandom = "0.2"