[package]
name = "server"
version = "0.1.0"
authors = ["Elliot W. <elliotwhybrow@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3.3.2"
serde = {version = "1.0.118", features = ["derive"]}
serde_json = "1.0.60"